// SVG Icons
const SVG={fire:'<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C8 6 4 10 4 14c0 4.42 3.58 8 8 8s8-3.58 8-8c0-4-4-8-8-12zm0 18c-3.31 0-6-2.69-6-6 0-2 2-4 3-5 0 2 1 3 2 3s2-1 2-3c1 1 3 3 3 5 0 3.31-2.69 6-6 6z"/></svg>',ice:'<svg viewBox="0 0 24 24" fill="currentColor"><path d="M22 11h-4.17l3.24-3.24-1.41-1.42L15 11h-2V9l4.66-4.66-1.42-1.41L13 6.17V2h-2v4.17L7.76 2.93 6.34 4.34 11 9v2H9L4.34 6.34 2.93 7.76 6.17 11H2v2h4.17l-3.24 3.24 1.41 1.42L9 13h2v2l-4.66 4.66 1.42 1.41L11 17.83V22h2v-4.17l3.24 3.24 1.42-1.41L13 15v-2h2l4.66 4.66 1.41-1.42L17.83 13H22z"/></svg>',arcane:'<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 2L4.5 20.29l.71.71L12 18l6.79 3 .71-.71z"/></svg>',dash:'<svg viewBox="0 0 24 24" fill="currentColor"><path d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>',ult:'<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 2L1 21h22L12 2z"/></svg>'};
const CLASS_SVG={pyromancer:SVG.fire,cryomancer:SVG.ice,arcanist:SVG.arcane};
const SPELL_SVG={fireball:'<svg viewBox="0 0 24 24" fill="#ff6b35"><circle cx="12" cy="12" r="8"/></svg>',flamewave:'<svg viewBox="0 0 24 24" fill="#ff6b35"><path d="M12 2C8 6 4 10 4 14c0 4.42 3.58 8 8 8s8-3.58 8-8c0-4-4-8-8-12z"/></svg>',frostbolt:'<svg viewBox="0 0 24 24" fill="#4ecdc4"><path d="M12 2l3 9h9l-7 5 3 9-8-6-8 6 3-9-7-5h9z"/></svg>',blizzard:'<svg viewBox="0 0 24 24" fill="#4ecdc4"><path d="M22 11h-4l3-3-1.4-1.4L15 11h-2V9l4.6-4.6L16.2 3 13 6.2V2h-2v4.2L7.8 3 6.4 4.4 11 9v2H9L4.4 6.6 3 8l3 3H2v2h4l-3 3 1.4 1.4L9 13h2v2l-4.6 4.6 1.4 1.4L11 17.8V22h2v-4.2l3.2 3.2 1.4-1.4L13 15v-2h2l4.6 4.6 1.4-1.4-3-3h4z"/></svg>',arcaneBlast:'<svg viewBox="0 0 24 24" fill="#9b5de5"><path d="M12 2L4.5 20.29l.71.71L12 18l6.79 3 .71-.71z"/></svg>',magicMissile:'<svg viewBox="0 0 24 24" fill="#9b5de5"><path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z"/></svg>',dash:'<svg viewBox="0 0 24 24" fill="#ffd93d"><path d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>',ultimate:'<svg viewBox="0 0 24 24" fill="#ffd93d"><path d="M12 2L1 21h22L12 2z"/></svg>'};

const SERVER_URL=(!window.location.hostname||window.location.protocol==='file:')?'http://localhost:3001':window.location.origin;
const canvas=document.getElementById('game-canvas'),ctx=canvas.getContext('2d');
const minimapCanvas=document.getElementById('minimap'),minimapCtx=minimapCanvas.getContext('2d');

let socket=null,playerId=null,playerData=null,selectedClass='pyromancer',selectedSkin='pyromancer_default';
let gameState={players:[],enemies:[],projectiles:[],xpOrbs:[],particles:[],damageNumbers:[],world:{width:4000,height:4000}};
let zones={},classes={},skins={},ranks=[];
let camera={x:0,y:0},screenShake={x:0,y:0,intensity:0},input={up:false,down:false,left:false,right:false};
let effects=[],meteorWarnings=[],mouseX=0,mouseY=0;
let settings={masterVolume:0.5,sfxEnabled:true,showZoneNames:true,showMinimap:true};
let audioCtx=null;

const defaultClasses={pyromancer:{id:'pyromancer',name:'Pyromancer',color:'#ff6b35',description:'Fire master. High damage, glass cannon.',dash:'Fire Dash',ultimate:'Meteor Strike'},cryomancer:{id:'cryomancer',name:'Cryomancer',color:'#4ecdc4',description:'Ice wizard. Crowd control specialist.',dash:'Frost Step',ultimate:'Ice Nova'},arcanist:{id:'arcanist',name:'Arcanist',color:'#9b5de5',description:'Arcane power. Balanced with AOE.',dash:'Blink',ultimate:'Arcane Barrage'}};
const COLORS={grass1:'#2d5a27',grass2:'#234d1f',enemy:{slime:'#4ade80',bat:'#a855f7',skeleton:'#e5e5e5',ghost:'#94a3b8',golem:'#78716c',spider:'#1a1a1a',necromancer:'#581c87',fireElemental:'#f97316',iceElemental:'#06b6d4',boss_slime:'#22c55e',boss_dragon:'#dc2626'}};

// Audio
function initAudio(){if(!audioCtx)try{audioCtx=new(window.AudioContext||window.webkitAudioContext)()}catch(e){}}
function playSound(type){if(!settings.sfxEnabled||!audioCtx||settings.masterVolume===0)return;try{const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.connect(gain);gain.connect(audioCtx.destination);const now=audioCtx.currentTime,vol=settings.masterVolume*0.12;const sounds={spell:()=>{osc.type='sine';osc.frequency.setValueAtTime(400,now);osc.frequency.exponentialRampToValueAtTime(200,now+0.1);gain.gain.setValueAtTime(vol,now);gain.gain.exponentialRampToValueAtTime(0.01,now+0.15);osc.start(now);osc.stop(now+0.15)},enemyDeath:()=>{osc.type='square';osc.frequency.setValueAtTime(300,now);osc.frequency.exponentialRampToValueAtTime(100,now+0.1);gain.gain.setValueAtTime(vol,now);gain.gain.exponentialRampToValueAtTime(0.01,now+0.12);osc.start(now);osc.stop(now+0.12)},xpPickup:()=>{osc.type='sine';osc.frequency.setValueAtTime(800,now);osc.frequency.setValueAtTime(1000,now+0.05);gain.gain.setValueAtTime(vol*0.5,now);gain.gain.exponentialRampToValueAtTime(0.01,now+0.1);osc.start(now);osc.stop(now+0.1)},levelUp:()=>{osc.type='sine';osc.frequency.setValueAtTime(523,now);osc.frequency.setValueAtTime(659,now+0.1);osc.frequency.setValueAtTime(784,now+0.2);gain.gain.setValueAtTime(vol,now);gain.gain.exponentialRampToValueAtTime(0.01,now+0.4);osc.start(now);osc.stop(now+0.4)},playerHit:()=>{osc.type='triangle';osc.frequency.setValueAtTime(100,now);osc.frequency.exponentialRampToValueAtTime(50,now+0.1);gain.gain.setValueAtTime(vol,now);gain.gain.exponentialRampToValueAtTime(0.01,now+0.15);osc.start(now);osc.stop(now+0.15)},dash:()=>{osc.type='sawtooth';osc.frequency.setValueAtTime(200,now);osc.frequency.exponentialRampToValueAtTime(600,now+0.08);gain.gain.setValueAtTime(vol*0.6,now);gain.gain.exponentialRampToValueAtTime(0.01,now+0.15);osc.start(now);osc.stop(now+0.15)},meteor:()=>{osc.type='sawtooth';osc.frequency.setValueAtTime(150,now);osc.frequency.exponentialRampToValueAtTime(30,now+0.3);gain.gain.setValueAtTime(vol*1.5,now);gain.gain.exponentialRampToValueAtTime(0.01,now+0.4);osc.start(now);osc.stop(now+0.4)},iceNova:()=>{osc.type='sine';osc.frequency.setValueAtTime(1200,now);osc.frequency.exponentialRampToValueAtTime(400,now+0.2);gain.gain.setValueAtTime(vol,now);gain.gain.exponentialRampToValueAtTime(0.01,now+0.25);osc.start(now);osc.stop(now+0.25)},bossSpawn:()=>{osc.type='sawtooth';osc.frequency.setValueAtTime(80,now);osc.frequency.setValueAtTime(100,now+0.3);gain.gain.setValueAtTime(vol*1.2,now);gain.gain.exponentialRampToValueAtTime(0.01,now+0.6);osc.start(now);osc.stop(now+0.6)}};if(sounds[type])sounds[type]()}catch(e){}}

// Canvas
function resizeCanvas(){canvas.width=window.innerWidth;canvas.height=window.innerHeight}
window.addEventListener('resize',resizeCanvas);resizeCanvas();

// Tabs
document.querySelectorAll('.tab-btn').forEach(btn=>{btn.addEventListener('click',()=>{document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(c=>c.classList.remove('active'));btn.classList.add('active');document.getElementById('tab-'+btn.dataset.tab).classList.add('active')})});

// Settings
function loadSettings(){const saved=localStorage.getItem('spellBrigadeSettings');if(saved)settings={...settings,...JSON.parse(saved)};document.getElementById('master-volume').value=settings.masterVolume*100;document.getElementById('game-volume').value=settings.masterVolume*100;document.getElementById('sfx-toggle').classList.toggle('on',settings.sfxEnabled);document.getElementById('zone-toggle').classList.toggle('on',settings.showZoneNames);document.getElementById('minimap-toggle').classList.toggle('on',settings.showMinimap);updateVolumeIcon()}
function saveSettings(){localStorage.setItem('spellBrigadeSettings',JSON.stringify(settings))}
function updateVolumeIcon(){const btn=document.getElementById('volume-btn');btn.innerHTML=settings.masterVolume===0||!settings.sfxEnabled?'<svg viewBox="0 0 24 24"><path d="M16.5 12c0-1.77-1.02-3.29-2.5-4.03v2.21l2.45 2.45c.03-.2.05-.41.05-.63zm2.5 0c0 .94-.2 1.82-.54 2.64l1.51 1.51C20.63 14.91 21 13.5 21 12c0-4.28-2.99-7.86-7-8.77v2.06c2.89.86 5 3.54 5 6.71zM4.27 3L3 4.27 7.73 9H3v6h4l5 5v-6.73l4.25 4.25c-.67.52-1.42.93-2.25 1.18v2.06c1.38-.31 2.63-.95 3.69-1.81L19.73 21 21 19.73l-9-9L4.27 3zM12 4L9.91 6.09 12 8.18V4z"/></svg>':'<svg viewBox="0 0 24 24"><path d="M3 9v6h4l5 5V4L7 9H3zm13.5 3c0-1.77-1.02-3.29-2.5-4.03v8.05c1.48-.73 2.5-2.25 2.5-4.02zM14 3.23v2.06c2.89.86 5 3.54 5 6.71s-2.11 5.85-5 6.71v2.06c4.01-.91 7-4.49 7-8.77s-2.99-7.86-7-8.77z"/></svg>'}
document.getElementById('master-volume').addEventListener('input',e=>{settings.masterVolume=e.target.value/100;document.getElementById('game-volume').value=e.target.value;updateVolumeIcon();saveSettings()});
document.getElementById('game-volume').addEventListener('input',e=>{settings.masterVolume=e.target.value/100;updateVolumeIcon();saveSettings()});
document.getElementById('volume-btn').addEventListener('click',()=>{settings.sfxEnabled=!settings.sfxEnabled;updateVolumeIcon();saveSettings()});
document.querySelectorAll('.toggle').forEach(toggle=>{toggle.addEventListener('click',()=>{toggle.classList.toggle('on');if(toggle.id==='sfx-toggle')settings.sfxEnabled=toggle.classList.contains('on');if(toggle.id==='zone-toggle')settings.showZoneNames=toggle.classList.contains('on');if(toggle.id==='minimap-toggle')settings.showMinimap=toggle.classList.contains('on');saveSettings()})});
loadSettings();

// Class/Skin Selection
function renderClassSelect(){const container=document.getElementById('class-select');container.innerHTML='';const classData=Object.keys(classes).length>0?classes:defaultClasses;for(const[id,data]of Object.entries(classData)){const card=document.createElement('div');card.className='class-card'+(id===selectedClass?' selected':'');card.style.setProperty('--class-color',data.color);card.innerHTML=`<div class="class-icon" style="color:${data.color};background:${data.color}20">${CLASS_SVG[id]||SVG.arcane}</div><h3 style="color:${data.color}">${data.name}</h3><p>${data.description}</p><div class="class-abilities"><div class="class-ability"><span style="color:${data.color}">${SVG.dash}</span>${data.dash||'Dash'}</div><div class="class-ability"><span style="color:${data.color}">${SVG.ult}</span>${data.ultimate||'Ultimate'}</div></div>`;card.addEventListener('click',()=>{selectedClass=id;selectedSkin=id+'_default';document.querySelectorAll('.class-card').forEach(c=>c.classList.remove('selected'));card.classList.add('selected');renderSkinSelect()});container.appendChild(card)}}

function renderSkinSelect(){const container=document.getElementById('skin-grid');container.innerHTML='';const totalXp=playerData?.totalXp||parseInt(localStorage.getItem('spellBrigadeTotalXp')||'0');const classColor=(classes[selectedClass]||defaultClasses[selectedClass])?.color||'#fff';const defaultSkins=[{id:selectedClass+'_default',name:'Default',color:classColor,requiredXp:0},{id:selectedClass+'_tier2',name:'Adept',color:'#a855f7',requiredXp:500},{id:selectedClass+'_tier3',name:'Master',color:'#fbbf24',requiredXp:2000},{id:selectedClass+'_tier4',name:'Legend',color:'#ef4444',requiredXp:5000}];const skinData=Object.keys(skins).length>0?Object.values(skins).filter(s=>s.class===selectedClass):defaultSkins;for(const skin of skinData){const unlocked=totalXp>=skin.requiredXp;const option=document.createElement('div');option.className='skin-option'+(skin.id===selectedSkin?' selected':'')+(!unlocked?' locked':'');option.style.background=skin.color+'25';option.innerHTML=`<span style="color:${skin.color}">${CLASS_SVG[selectedClass]||SVG.arcane}</span>`;option.title=skin.name+(!unlocked?' ('+skin.requiredXp+' XP)':'');if(unlocked)option.addEventListener('click',()=>{selectedSkin=skin.id;document.querySelectorAll('.skin-option').forEach(o=>o.classList.remove('selected'));option.classList.add('selected')});container.appendChild(option)}}
renderClassSelect();renderSkinSelect();

// Socket
function connectSocket(){socket=io(SERVER_URL,{reconnection:true,reconnectionDelay:1000});
socket.on('connect',()=>{document.getElementById('connection-status').className='connected';document.getElementById('connection-status').innerHTML='<svg viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="12" r="8"/></svg><span>Connected</span>'});
socket.on('disconnect',()=>{document.getElementById('connection-status').className='disconnected';document.getElementById('connection-status').innerHTML='<svg viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="12" r="8"/></svg><span>Disconnected</span>'});
socket.on('joined',data=>{playerId=data.playerId;playerData=data.player;localStorage.setItem('spellBrigadePlayerId',playerId);localStorage.setItem('spellBrigadeTotalXp',playerData.totalXp||0);if(data.zones)zones=data.zones;if(data.classes)classes=data.classes;if(data.skins)skins=data.skins;if(data.ranks)ranks=data.ranks;if(data.world)gameState.world=data.world;document.getElementById('title-screen').classList.add('hidden');document.getElementById('hud').style.display='block';document.getElementById('zone-indicator').style.display=settings.showZoneNames?'flex':'none';document.getElementById('volume-control').style.display='flex';updateHUD();render()});
socket.on('gameState',state=>{gameState={...gameState,...state};const me=state.players?.find(p=>p.id===playerId);if(me){playerData=me;updateHUD();updateZoneIndicator()}});
socket.on('levelUp',data=>{document.getElementById('new-level').textContent=data.level;document.getElementById('level-up').classList.add('show');playSound('levelUp');setTimeout(()=>document.getElementById('level-up').classList.remove('show'),2000)});
socket.on('died',data=>{document.getElementById('killed-by').textContent=data.killedBy;document.getElementById('death-level').textContent=data.level;document.getElementById('death-kills').textContent=playerData?.kills||0;document.getElementById('death-xp').textContent=playerData?.totalXp||0;document.getElementById('death-screen').classList.remove('hidden')});
socket.on('damaged',data=>{screenShake.intensity=Math.min(15,data.amount/2);playSound('playerHit')});
socket.on('sound',data=>playSound(data.type));
socket.on('explosion',data=>{effects.push({type:'explosion',x:data.x,y:data.y,radius:data.radius,color:data.color||'#f97316',startTime:Date.now(),duration:500});playSound('meteor');screenShake.intensity=12});
socket.on('meteorWarning',data=>meteorWarnings.push({x:data.x,y:data.y,radius:data.radius,startTime:Date.now(),delay:data.delay}));
socket.on('iceNova',data=>{effects.push({type:'iceNova',x:data.x,y:data.y,radius:data.radius,startTime:Date.now(),duration:400});playSound('iceNova')});
socket.on('dashTrail',data=>effects.push({type:'trail',startX:data.startX,startY:data.startY,endX:data.endX,endY:data.endY,color:data.color,startTime:Date.now(),duration:300}));
socket.on('bossSpawn',()=>playSound('bossSpawn'));
socket.on('respawned',()=>document.getElementById('death-screen').classList.add('hidden'))}
connectSocket();

// Events
document.getElementById('play-btn').addEventListener('click',()=>{initAudio();const name=document.getElementById('player-name').value.trim()||'Wizard'+Math.floor(Math.random()*9000+1000);socket.emit('join',{playerId:localStorage.getItem('spellBrigadePlayerId'),playerName:name,playerClass:selectedClass,selectedSkin})});
document.getElementById('respawn-btn').addEventListener('click',()=>socket.emit('respawn'));

// Input
const keyMap={'KeyW':'up','ArrowUp':'up','KeyS':'down','ArrowDown':'down','KeyA':'left','ArrowLeft':'left','KeyD':'right','ArrowRight':'right'};
window.addEventListener('mousemove',e=>{mouseX=e.clientX;mouseY=e.clientY});
window.addEventListener('keydown',e=>{initAudio();const dir=keyMap[e.code];if(dir&&!input[dir]){input[dir]=true;if(socket)socket.emit('input',input)}if(e.code==='Space'&&socket&&playerId){e.preventDefault();socket.emit('dash',{targetX:mouseX+camera.x,targetY:mouseY+camera.y});playSound('dash')}if(e.code==='KeyQ'&&socket&&playerId)socket.emit('ultimate',{targetX:mouseX+camera.x,targetY:mouseY+camera.y})});
window.addEventListener('keyup',e=>{const dir=keyMap[e.code];if(dir&&input[dir]){input[dir]=false;if(socket)socket.emit('input',input)}});
canvas.addEventListener('click',()=>initAudio());

// HUD
function updateHUD(){if(!playerData)return;const classData=classes[playerData.class]||defaultClasses[playerData.class];const classColor=classData?.color||'#fff';document.getElementById('hud-avatar').innerHTML=`<span style="color:${classColor}">${CLASS_SVG[playerData.class]||SVG.arcane}</span>`;document.getElementById('hud-avatar').style.background=classColor+'25';document.getElementById('hud-name').textContent=playerData.name;const rank=playerData.rank||{title:'Novice'};document.getElementById('hud-rank').innerHTML=`<svg viewBox="0 0 24 24" fill="#ffd93d"><path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z"/></svg>${rank.title||'Novice'} • Lv ${playerData.level}`;document.getElementById('hp-text').textContent=Math.floor(playerData.health)+'/'+playerData.maxHealth;document.getElementById('hp-bar').style.width=(playerData.health/playerData.maxHealth*100)+'%';const xpToLevel=playerData.xpToLevel||100;document.getElementById('xp-text').textContent=playerData.xp+'/'+xpToLevel;document.getElementById('xp-bar').style.width=(playerData.xp/xpToLevel*100)+'%';document.getElementById('kills-stat').textContent=playerData.kills||0;document.getElementById('deaths-stat').textContent=playerData.deaths||0;document.getElementById('total-xp-stat').textContent=playerData.totalXp||0;
if(playerData.cooldowns){const el=document.getElementById('cooldowns');el.innerHTML='';const order=[...Object.keys(playerData.cooldowns).filter(i=>!['dash','ultimate'].includes(i)),'dash','ultimate'].filter(i=>playerData.cooldowns[i]);for(const id of order){const cd=playerData.cooldowns[id];if(!cd)continue;const slot=document.createElement('div');slot.className='cooldown-slot'+(cd.ready?' ready':'');slot.innerHTML=`${SPELL_SVG[id]||SPELL_SVG.dash}<div class="cooldown-overlay" style="height:${cd.ready?0:cd.remaining/cd.total*100}%"></div>${id==='dash'?'<span class="cooldown-key">SPC</span>':id==='ultimate'?'<span class="cooldown-key">Q</span>':''}`;el.appendChild(slot)}}}

function updateZoneIndicator(){if(!settings.showZoneNames){document.getElementById('zone-indicator').style.display='none';return}document.getElementById('zone-indicator').style.display='flex';const me=gameState.players?.find(p=>p.id===playerId);if(!me)return;const dist=Math.sqrt((me.x-2000)**2+(me.y-2000)**2);let zone={name:'Sanctuary',color:'#22c55e',rec:0};if(dist<=250)zone={name:'Sanctuary',color:'#22c55e',rec:0};else if(dist<=800)zone={name:'Peaceful Meadow',color:'#84cc16',rec:1};else if(dist<=1400)zone={name:'Dark Forest',color:'#166534',rec:5};else if(dist<=1800)zone={name:'Volcanic Wastes',color:'#dc2626',rec:10};else if(dist<=2200)zone={name:'Frozen Expanse',color:'#0ea5e9',rec:15};else zone={name:'The Abyss',color:'#581c87',rec:20};document.getElementById('zone-icon').style.fill=zone.color;document.getElementById('zone-name').textContent=zone.name;document.getElementById('zone-warning').innerHTML=playerData&&playerData.level<zone.rec?`<svg viewBox="0 0 24 24" fill="currentColor"><path d="M1 21h22L12 2 1 21zm12-3h-2v-2h2v2zm0-4h-2v-4h2v4z"/></svg>Lv ${zone.rec}+`:''}

// Render
function lerp(a,b,t){return a+(b-a)*t}

function render(){const{width,height}=canvas;const{world}=gameState;const me=gameState.players?.find(p=>p.id===playerId);
if(me){camera.x=lerp(camera.x,me.x-width/2,0.1);camera.y=lerp(camera.y,me.y-height/2,0.1);camera.x=Math.max(0,Math.min(world.width-width,camera.x));camera.y=Math.max(0,Math.min(world.height-height,camera.y))}
if(screenShake.intensity>0){screenShake.x=(Math.random()-0.5)*screenShake.intensity*2;screenShake.y=(Math.random()-0.5)*screenShake.intensity*2;screenShake.intensity*=0.9;if(screenShake.intensity<0.5)screenShake.intensity=0}else{screenShake.x=0;screenShake.y=0}
const cam={x:camera.x+screenShake.x,y:camera.y+screenShake.y};
ctx.fillStyle='#0f0f1a';ctx.fillRect(0,0,width,height);
const cx=2000-cam.x,cy=2000-cam.y;
[{r:2200,c:'#581c87'},{r:1800,c:'#0ea5e9'},{r:1400,c:'#dc2626'},{r:800,c:'#166534'},{r:250,c:'#84cc16'}].forEach(z=>{ctx.beginPath();ctx.arc(cx,cy,z.r,0,Math.PI*2);ctx.fillStyle=z.c+'12';ctx.fill()});
const tileSize=64,startX=Math.floor(cam.x/tileSize)*tileSize,startY=Math.floor(cam.y/tileSize)*tileSize;
for(let x=startX;x<cam.x+width+tileSize;x+=tileSize){for(let y=startY;y<cam.y+height+tileSize;y+=tileSize){ctx.fillStyle=((x/tileSize)+(y/tileSize))%2===0?COLORS.grass1:COLORS.grass2;ctx.fillRect(x-cam.x,y-cam.y,tileSize,tileSize)}}
ctx.beginPath();ctx.arc(cx,cy,250,0,Math.PI*2);ctx.fillStyle='rgba(34,197,94,0.15)';ctx.fill();ctx.strokeStyle='rgba(34,197,94,0.5)';ctx.lineWidth=3;ctx.setLineDash([10,5]);ctx.stroke();ctx.setLineDash([]);
ctx.strokeStyle='#ef4444';ctx.lineWidth=4;ctx.setLineDash([20,10]);ctx.strokeRect(-cam.x,-cam.y,world.width,world.height);ctx.setLineDash([]);

// Enemies
for(const enemy of gameState.enemies||[]){const sx=enemy.x-cam.x,sy=enemy.y-cam.y;if(sx<-60||sx>width+60||sy<-60||sy>height+60)continue;const isBoss=enemy.isBoss,bounce=enemy.isFrozen?0:Math.sin((enemy.animFrame||0)*Math.PI/2)*2;const color=COLORS.enemy[enemy.type]||'#ff0000',size=isBoss?2:1;ctx.beginPath();ctx.ellipse(sx,sy+8,12*size,6*size,0,0,Math.PI*2);ctx.fillStyle='rgba(0,0,0,0.3)';ctx.fill();ctx.beginPath();ctx.arc(sx,sy-bounce,(14+(isBoss?20:0))*size,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();ctx.strokeStyle='rgba(0,0,0,0.3)';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(sx-4*size,sy-4*size-bounce,3*size,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(sx+4*size,sy-4*size-bounce,3*size,0,Math.PI*2);ctx.fill();ctx.fillStyle='#000';ctx.beginPath();ctx.arc(sx-4*size,sy-4*size-bounce,1.5*size,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(sx+4*size,sy-4*size-bounce,1.5*size,0,Math.PI*2);ctx.fill();if(enemy.health<enemy.maxHealth||isBoss){const hbW=isBoss?60:28,hbY=sy-(isBoss?50:30);ctx.fillStyle='rgba(0,0,0,0.5)';ctx.fillRect(sx-hbW/2-1,hbY-1,hbW+2,isBoss?8:6);ctx.fillStyle='#1a1a2e';ctx.fillRect(sx-hbW/2,hbY,hbW,isBoss?6:4);ctx.fillStyle=isBoss?'#fbbf24':'#ef4444';ctx.fillRect(sx-hbW/2,hbY,hbW*enemy.health/enemy.maxHealth,isBoss?6:4)}if(isBoss){ctx.fillStyle='#fbbf24';ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.fillText('BOSS',sx,sy-60)}if(enemy.isFrozen){ctx.beginPath();ctx.arc(sx,sy,22,0,Math.PI*2);ctx.strokeStyle='#87ceeb';ctx.lineWidth=3;ctx.stroke()}if(enemy.isSlowed&&!enemy.isFrozen){ctx.beginPath();ctx.arc(sx,sy-bounce,20,0,Math.PI*2);ctx.strokeStyle='#4ecdc4';ctx.lineWidth=2;ctx.setLineDash([4,4]);ctx.stroke();ctx.setLineDash([])}}

// Projectiles
for(const proj of gameState.projectiles||[]){const px=proj.x-cam.x,py=proj.y-cam.y;if(px<-50||px>width+50||py<-50||py>height+50)continue;ctx.beginPath();ctx.arc(px,py,proj.radius+10,0,Math.PI*2);const grad=ctx.createRadialGradient(px,py,0,px,py,proj.radius+10);grad.addColorStop(0,proj.color||'#fff');grad.addColorStop(1,'transparent');ctx.fillStyle=grad;ctx.fill();ctx.beginPath();ctx.arc(px,py,proj.radius,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill()}

// XP Orbs
for(const orb of gameState.xpOrbs||[]){const ox=orb.x-cam.x,oy=orb.y-cam.y;if(ox<-20||ox>width+20||oy<-20||oy>height+20)continue;const pulse=Math.sin(Date.now()/150+orb.x)*0.3+0.7,r=6+pulse*2;ctx.beginPath();ctx.arc(ox,oy,r+6,0,Math.PI*2);const glow=ctx.createRadialGradient(ox,oy,0,ox,oy,r+6);glow.addColorStop(0,'rgba(59,130,246,'+(0.6*pulse)+')');glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.fill();ctx.beginPath();ctx.arc(ox,oy,r,0,Math.PI*2);ctx.fillStyle='#3b82f6';ctx.fill();ctx.beginPath();ctx.arc(ox-r*0.3,oy-r*0.3,r*0.3,0,Math.PI*2);ctx.fillStyle='rgba(255,255,255,0.6)';ctx.fill()}

// Players
for(const player of gameState.players||[]){if(player.health<=0)continue;const px=player.x-cam.x,py=player.y-cam.y;if(px<-50||px>width+50||py<-50||py>height+50)continue;const isMe=player.id===playerId;const classData=classes[player.class]||defaultClasses[player.class];const classColor=classData?.color||'#fff';const bob=player.state==='walk'?Math.sin((player.animFrame||0)*Math.PI/2)*2:0;ctx.beginPath();ctx.ellipse(px,py+12,16,8,0,0,Math.PI*2);ctx.fillStyle='rgba(0,0,0,0.3)';ctx.fill();ctx.fillStyle=classColor;ctx.beginPath();ctx.moveTo(px,py-12-bob);ctx.lineTo(px-14,py+14);ctx.lineTo(px+14,py+14);ctx.closePath();ctx.fill();ctx.beginPath();ctx.arc(px,py-18-bob,11,0,Math.PI*2);ctx.fillStyle='#fcd5ce';ctx.fill();ctx.fillStyle=classColor;ctx.beginPath();ctx.moveTo(px,py-42-bob);ctx.lineTo(px-16,py-16-bob);ctx.lineTo(px+16,py-16-bob);ctx.closePath();ctx.fill();ctx.fillStyle='#333';ctx.beginPath();ctx.arc(px-3,py-19-bob,2,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(px+3,py-19-bob,2,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 11px sans-serif';ctx.textAlign='center';ctx.fillText(player.name,px,py+28);ctx.fillStyle='#ffd93d';ctx.font='10px sans-serif';ctx.fillText('Lv.'+player.level,px,py+40);if(!isMe||player.health<player.maxHealth){ctx.fillStyle='rgba(0,0,0,0.5)';ctx.fillRect(px-19,py-51-bob,38,7);ctx.fillStyle='#1a1a2e';ctx.fillRect(px-18,py-50-bob,36,5);ctx.fillStyle='#ef4444';ctx.fillRect(px-18,py-50-bob,36*player.health/player.maxHealth,5)}if(isMe){ctx.beginPath();ctx.arc(px,py,28,0,Math.PI*2);ctx.strokeStyle=classColor+'50';ctx.lineWidth=3;ctx.stroke()}}

// Particles
for(const p of gameState.particles||[]){const ppx=p.x-cam.x,ppy=p.y-cam.y;if(ppx<-20||ppx>width+20||ppy<-20||ppy>height+20)continue;ctx.beginPath();ctx.arc(ppx,ppy,(p.radius||3)*(p.alpha||1),0,Math.PI*2);ctx.fillStyle=p.color+Math.floor((p.alpha||1)*255).toString(16).padStart(2,'0');ctx.fill()}

// Damage numbers
for(const dmg of gameState.damageNumbers||[]){const dx=dmg.x-cam.x,dy=dmg.y-cam.y;if(dx<-50||dx>width+50||dy<-50||dy>height+50)continue;ctx.font='bold 16px sans-serif';ctx.textAlign='center';ctx.fillStyle='rgba(0,0,0,'+(dmg.alpha||1)*0.5+')';ctx.fillText(dmg.amount,dx+1,dy+1);ctx.fillStyle=dmg.isCrit?'rgba(255,215,0,'+(dmg.alpha||1)+')':'rgba(255,255,255,'+(dmg.alpha||1)+')';ctx.fillText(dmg.amount,dx,dy)}

// Effects
const now=Date.now();
meteorWarnings=meteorWarnings.filter(m=>{const elapsed=now-m.startTime;if(elapsed>m.delay)return false;const mx=m.x-cam.x,my=m.y-cam.y,progress=elapsed/m.delay;ctx.beginPath();ctx.arc(mx,my,m.radius,0,Math.PI*2);ctx.strokeStyle='rgba(255,100,0,'+(0.5+Math.sin(elapsed*0.02)*0.3)+')';ctx.lineWidth=3;ctx.setLineDash([10,5]);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(mx,my,m.radius*(1-progress),0,Math.PI*2);ctx.fillStyle='rgba(255,100,0,'+(0.2*(1-progress))+')';ctx.fill();return true});

effects=effects.filter(ef=>{const elapsed=now-ef.startTime;if(elapsed>ef.duration)return false;const progress=elapsed/ef.duration,alpha=1-progress;if(ef.type==='explosion'){const ex=ef.x-cam.x,ey=ef.y-cam.y,cr=ef.radius*(0.5+progress*0.5);ctx.beginPath();ctx.arc(ex,ey,cr,0,Math.PI*2);const gr=ctx.createRadialGradient(ex,ey,0,ex,ey,cr);gr.addColorStop(0,ef.color+Math.floor(alpha*200).toString(16).padStart(2,'0'));gr.addColorStop(0.5,ef.color+Math.floor(alpha*100).toString(16).padStart(2,'0'));gr.addColorStop(1,'transparent');ctx.fillStyle=gr;ctx.fill();if(progress<0.3){ctx.beginPath();ctx.arc(ex,ey,cr*0.3*(1-progress/0.3),0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill()}}else if(ef.type==='iceNova'){const ex=ef.x-cam.x,ey=ef.y-cam.y,cr=ef.radius*progress;ctx.beginPath();ctx.arc(ex,ey,cr,0,Math.PI*2);ctx.strokeStyle='rgba(78,205,196,'+alpha+')';ctx.lineWidth=8*alpha;ctx.stroke();ctx.beginPath();ctx.arc(ex,ey,cr*0.8,0,Math.PI*2);ctx.fillStyle='rgba(78,205,196,'+(alpha*0.3)+')';ctx.fill()}else if(ef.type==='trail'){ctx.beginPath();ctx.moveTo(ef.startX-cam.x,ef.startY-cam.y);ctx.lineTo(ef.endX-cam.x,ef.endY-cam.y);ctx.strokeStyle=ef.color+Math.floor(alpha*255).toString(16).padStart(2,'0');ctx.lineWidth=20*alpha;ctx.lineCap='round';ctx.stroke()}return true});

// Minimap
if(settings.showMinimap){minimapCanvas.style.display='block';const mmW=minimapCanvas.width,mmH=minimapCanvas.height,scale=mmW/world.width;minimapCtx.fillStyle='#1a1a2e';minimapCtx.fillRect(0,0,mmW,mmH);const mcx=2000*scale,mcy=2000*scale;[{r:250,c:'#22c55e'},{r:800,c:'#84cc16'},{r:1400,c:'#166534'},{r:1800,c:'#dc2626'},{r:2200,c:'#0ea5e9'}].forEach(ring=>{minimapCtx.beginPath();minimapCtx.arc(mcx,mcy,ring.r*scale,0,Math.PI*2);minimapCtx.strokeStyle=ring.c+'60';minimapCtx.lineWidth=1;minimapCtx.stroke()});for(const e of gameState.enemies||[]){minimapCtx.beginPath();minimapCtx.arc(e.x*scale,e.y*scale,e.isBoss?4:2,0,Math.PI*2);minimapCtx.fillStyle=e.isBoss?'#fbbf24':'#ef4444';minimapCtx.fill()}for(const p of gameState.players||[]){if(p.health<=0)continue;minimapCtx.beginPath();minimapCtx.arc(p.x*scale,p.y*scale,p.id===playerId?4:3,0,Math.PI*2);minimapCtx.fillStyle=p.id===playerId?'#ffd93d':'#3b82f6';minimapCtx.fill()}minimapCtx.strokeStyle='rgba(255,255,255,0.3)';minimapCtx.lineWidth=1;minimapCtx.strokeRect(camera.x*scale,camera.y*scale,canvas.width*scale,canvas.height*scale)}else{minimapCanvas.style.display='none'}
requestAnimationFrame(render)}
