// ===========================================
// CLASSES
// ===========================================

export const CLASSES = {
  pyromancer: {
    id: 'pyromancer',
    name: 'Pyromancer',
    color: '#ff6b35',
    secondaryColor: '#ffaa00',
    baseHealth: 80,
    baseSpeed: 195,
    spells: ['fireball', 'flamewave'],
    description: 'Master of fire magic. High damage, lower health.',
    bodyStyle: 'elemental',
    headgear: 'pointyHat',
    projectileShape: 'orb',
    passive: { id: 'ignite', name: 'Ignite', description: 'Attacks have 20% chance to ignite enemies, dealing burn damage over 3s.' },
    dashAbility: {
      id: 'fireDash',
      name: 'Fire Dash',
      description: 'Dash forward leaving a trail of fire that burns enemies.',
      cooldown: 4000,
      distance: 200,
      damage: 15,
      trailDuration: 1000,
    },
    ultimateAbility: {
      id: 'meteor',
      name: 'Meteor Strike',
      description: 'Call down a massive meteor that explodes on impact.',
      cooldown: 20000,
      damage: 100,
      radius: 150,
      delay: 1000, // Warning before impact
    },
  },
  cryomancer: {
    id: 'cryomancer',
    name: 'Cryomancer',
    color: '#4ecdc4',
    secondaryColor: '#a0e9e4',
    baseHealth: 90,
    baseSpeed: 185,
    spells: ['frostbolt', 'blizzard'],
    description: 'Ice wizard. Balanced stats with slowing effects.',
    bodyStyle: 'wizard',
    headgear: 'crown',
    projectileShape: 'shard',
    passive: { id: 'shatter', name: 'Shatter', description: 'Killing frozen enemies triggers an ice explosion that damages and slows nearby foes.' },
    dashAbility: {
      id: 'frostStep',
      name: 'Frost Step',
      description: 'Teleport forward and freeze nearby enemies on arrival.',
      cooldown: 5000,
      distance: 180,
      freezeDuration: 2000,
      freezeRadius: 60,
    },
    ultimateAbility: {
      id: 'iceNova',
      name: 'Ice Nova',
      description: 'Unleash an ice explosion that freezes all enemies in range.',
      cooldown: 25000,
      damage: 50,
      radius: 200,
      freezeDuration: 3000,
    },
  },
  arcanist: {
    id: 'arcanist',
    name: 'Arcanist',
    color: '#9b5de5',
    secondaryColor: '#e056fd',
    baseHealth: 100,
    baseSpeed: 175,
    spells: ['arcaneBlast', 'magicMissile'],
    description: 'Pure arcane power. Tanky with AOE damage.',
    bodyStyle: 'wizard',
    headgear: 'halo',
    projectileShape: 'orb',
    passive: { id: 'arcane_echo', name: 'Arcane Echo', description: 'Every 4th spell cast releases an arcane echo dealing bonus AOE damage.' },
    dashAbility: {
      id: 'blink',
      name: 'Blink',
      description: 'Instantly teleport forward with brief invulnerability.',
      cooldown: 6000,
      distance: 250,
      invulnerable: true, // Brief invulnerability
    },
    ultimateAbility: {
      id: 'arcaneBarrage',
      name: 'Arcane Barrage',
      description: 'Unleash a barrage of homing arcane missiles.',
      cooldown: 18000,
      missiles: 12,
      damagePerMissile: 20,
      duration: 2000,
    },
  },
  
  // === Void Lord ===
  voidlord: {
    id: 'voidlord',
    name: 'Void Lord',
    color: '#1a0a2e',
    secondaryColor: '#ff00ff',
    baseHealth: 95,
    baseSpeed: 190,
    spells: ['voidBolt', 'annihilate'],
    description: 'Master of the void. Wields dark energy that pierces through all.',
    bodyStyle: 'elemental',
    headgear: 'horns',
    projectileShape: 'wisp',
    passive: { id: 'void_leech', name: 'Void Leech', description: 'All damage heals you for 8% of damage dealt.' },
    dashAbility: {
      id: 'voidShift',
      name: 'Void Shift',
      description: 'Phase through the void, becoming invulnerable and dealing damage on arrival.',
      cooldown: 5000,
      distance: 200,
      invulnerable: true,
      damageOnArrival: 25,
      damageRadius: 60,
    },
    ultimateAbility: {
      id: 'voidRift',
      name: 'Void Rift',
      description: 'Tear open a massive rift that pulls enemies in and deals heavy damage.',
      cooldown: 22000,
      damage: 80,
      radius: 200,
      pullForce: 100,
      duration: 2500,
    },
  },
  
  // === Shadow Archer ===
  shadowarcher: {
    id: 'shadowarcher',
    name: 'Shadow Archer',
    color: '#334155',
    secondaryColor: '#dc2626',
    baseHealth: 75,
    baseSpeed: 165,
    spells: ['shadowArrow', 'piercingVolley'],
    description: 'Agile ranged hunter. Piercing arrows shred groups.',
    icon: '🏹',
    bodyStyle: 'archer',
    headgear: 'hood',
    projectileShape: 'arrow',
    passive: { id: 'precision', name: 'Precision', description: '15% chance for attacks to critically strike for 2x damage.' },
    dashAbility: {
      id: 'shadowStep',
      name: 'Shadow Step',
      description: 'Vanish into shadow and reappear at target.',
      cooldown: 6000,
      distance: 180,
      invulnerable: false,
      damageOnArrival: 12,
      damageRadius: 40,
    },
    ultimateAbility: {
      id: 'arrowStorm',
      name: 'Arrow Storm',
      description: 'Rain down a storm of shadow arrows over an area.',
      cooldown: 25000,
      damage: 45,
      radius: 200,
      duration: 2000,
      waves: 4,
    },
  },
  
  // === The Brute ===
  brute: {
    id: 'brute',
    name: 'The Brute',
    color: '#b45309',
    secondaryColor: '#fbbf24',
    baseHealth: 130,
    baseSpeed: 170,
    spells: ['dumbbellThrow', 'groundPound'],
    description: 'Pure muscle. Throws dumbbells. Never skips any day.',
    icon: '💪',
    bodyStyle: 'hulk',
    headgear: 'headband',
    projectileShape: 'thrown',
    passive: { id: 'bloodlust', name: 'Bloodlust', description: 'Each kill grants +5% damage and +3% speed for 10s. Stacks up to 5x.' },
    dashAbility: {
      id: 'shoulderCharge',
      name: 'Shoulder Charge',
      description: 'Charge forward like a freight train, flattening everything.',
      cooldown: 4000,
      distance: 220,
      invulnerable: true,
      damageOnArrival: 30,
      damageRadius: 70,
    },
    ultimateAbility: {
      id: 'gainsMode',
      name: 'GAINS MODE',
      description: 'Flex so hard reality bends. Massive size, damage, and speed boost.',
      cooldown: 22000,
      damage: 80,
      radius: 200,
      duration: 5000,
    },
  },
  // === SWORDSMAN CLASS ===
  swordsman: {
    id: 'swordsman',
    name: 'Swordsman',
    color: '#708090',
    secondaryColor: '#c0c0c0',
    baseHealth: 110,
    baseSpeed: 195,
    spells: ['daggerThrow', 'axeHurl'],
    description: 'Steel and speed. Hurls blades and closes the gap.',
    icon: '⚔️',
    bodyStyle: 'warrior',
    headgear: 'helmet',
    projectileShape: 'bolt',
    passive: { id: 'riposte', name: 'Riposte', description: 'When hit, 20% chance to instantly counter-attack nearby enemies for 50% weapon damage.' },
    dashAbility: {
      id: 'bladeRush',
      name: 'Blade Rush',
      description: 'Dash forward slashing everything in your path.',
      cooldown: 4500,
      distance: 200,
      damage: 20,
      trailDuration: 600,
    },
    ultimateAbility: {
      id: 'whirlwindSlash',
      name: 'Whirlwind Slash',
      description: 'Spin with blades extended, cutting down everything nearby.',
      cooldown: 20000,
      damage: 70,
      radius: 180,
    },
    abilities: { 1: 'riposte', 2: 'executionersStrike', 3: 'bladestorm' },
  },
};

