// ===========================================
// CLASSES
// ===========================================

export const CLASSES = {
  pyromancer: {
    id: 'pyromancer',
    name: 'Pyromancer',
    color: '#ff6b35',
    baseHealth: 80,
    baseSpeed: 195,
    spells: ['fireball', 'flamewave'],
    description: 'Master of fire magic. High damage, lower health.',
    dashAbility: {
      id: 'fireDash',
      name: 'Fire Dash',
      description: 'Dash forward leaving a trail of fire that burns enemies.',
      cooldown: 4000,
      distance: 200,
      damage: 15,
      trailDuration: 1000,
    },
    ultimateAbility: {
      id: 'meteor',
      name: 'Meteor Strike',
      description: 'Call down a massive meteor that explodes on impact.',
      cooldown: 20000,
      damage: 100,
      radius: 150,
      delay: 1000, // Warning before impact
    },
  },
  cryomancer: {
    id: 'cryomancer',
    name: 'Cryomancer',
    color: '#4ecdc4',
    baseHealth: 90,
    baseSpeed: 185,
    spells: ['frostbolt', 'blizzard'],
    description: 'Ice wizard. Balanced stats with slowing effects.',
    dashAbility: {
      id: 'frostStep',
      name: 'Frost Step',
      description: 'Teleport forward and freeze nearby enemies on arrival.',
      cooldown: 5000,
      distance: 180,
      freezeDuration: 2000,
      freezeRadius: 60,
    },
    ultimateAbility: {
      id: 'iceNova',
      name: 'Ice Nova',
      description: 'Unleash an ice explosion that freezes all enemies in range.',
      cooldown: 25000,
      damage: 50,
      radius: 200,
      freezeDuration: 3000,
    },
  },
  arcanist: {
    id: 'arcanist',
    name: 'Arcanist',
    color: '#9b5de5',
    baseHealth: 100,
    baseSpeed: 175,
    spells: ['arcaneBlast', 'magicMissile'],
    description: 'Pure arcane power. Tanky with AOE damage.',
    dashAbility: {
      id: 'blink',
      name: 'Blink',
      description: 'Instantly teleport forward with brief invulnerability.',
      cooldown: 6000,
      distance: 250,
      invulnerable: true, // Brief invulnerability
    },
    ultimateAbility: {
      id: 'arcaneBarrage',
      name: 'Arcane Barrage',
      description: 'Unleash a barrage of homing arcane missiles.',
      cooldown: 18000,
      missiles: 12,
      damagePerMissile: 20,
      duration: 2000,
    },
  },
  
  // === UNLOCKABLE CLASS - After Dragon Kill ===
  voidlord: {
    id: 'voidlord',
    name: 'Void Lord',
    color: '#1a0a2e',
    secondaryColor: '#ff00ff',
    baseHealth: 95,
    baseSpeed: 190,
    spells: ['voidBolt', 'annihilate'],
    description: 'Master of the void. Unlocked by slaying the Dragon.',
    hidden: true, // Hidden until dragon is killed
    requiresDragonKill: true,
    dashAbility: {
      id: 'voidShift',
      name: 'Void Shift',
      description: 'Phase through the void, becoming invulnerable and dealing damage on arrival.',
      cooldown: 5000,
      distance: 200,
      invulnerable: true,
      damageOnArrival: 25,
      damageRadius: 60,
    },
    ultimateAbility: {
      id: 'voidRift',
      name: 'Void Rift',
      description: 'Tear open a massive rift that pulls enemies in and deals heavy damage.',
      cooldown: 22000,
      damage: 80,
      radius: 200,
      pullForce: 100,
      duration: 2500,
    },
  },
  
  // === UNLOCKABLE CLASS - Shadow Archer (Unlocked after Dragon Kill) ===
  shadowarcher: {
    id: 'shadowarcher',
    name: 'Shadow Archer',
    color: '#334155',
    secondaryColor: '#dc2626',
    baseHealth: 75,
    baseSpeed: 200,
    spells: ['shadowArrow', 'piercingVolley'],
    description: 'Deadly ranged hunter. Piercing arrows shred groups.',
    requiresDragonKill: true,
    hidden: true,
    icon: '🏹',
    dashAbility: {
      id: 'shadowStep',
      name: 'Shadow Step',
      description: 'Vanish into shadow and reappear at target.',
      cooldown: 5000,
      distance: 220,
      invulnerable: true,
      damageOnArrival: 20,
      damageRadius: 50,
    },
    ultimateAbility: {
      id: 'arrowStorm',
      name: 'Arrow Storm',
      description: 'Rain down a storm of shadow arrows over an area.',
      cooldown: 22000,
      damage: 70,
      radius: 250,
      duration: 2000,
      waves: 5,
    },
  },
  
  // === ADMIN CLASS - The Brute ===
  brute: {
    id: 'brute',
    name: 'The Brute',
    color: '#b45309',
    secondaryColor: '#fbbf24',
    baseHealth: 250,
    baseSpeed: 280,
    spells: ['dumbbellThrow', 'groundPound'],
    description: 'Pure muscle. Throws dumbbells. Never skips any day.',
    isAdmin: true,
    hidden: true,
    canPvP: true,
    icon: '💪',
    dashAbility: {
      id: 'shoulderCharge',
      name: 'Shoulder Charge',
      description: 'Charge forward like a freight train, flattening everything.',
      cooldown: 2500,
      distance: 350,
      invulnerable: true,
      damageOnArrival: 50,
      damageRadius: 90,
    },
    ultimateAbility: {
      id: 'gainsMode',
      name: 'GAINS MODE',
      description: 'Flex so hard reality bends. Massive size, damage, and speed boost.',
      cooldown: 12000,
      damage: 120,
      radius: 300,
      duration: 5000,
    },
  },
};

