// ===========================================
// ENEMIES
// ===========================================

export const ENEMY_TYPES = {
  slime: {
    id: 'slime',
    name: 'Slime',
    health: 35,
    damage: 8,
    speed: 45,
    radius: 14,
    xp: 10,
    color: '#4ade80',
    behavior: 'chase',
  },
  bat: {
    id: 'bat',
    name: 'Bat',
    health: 20,
    damage: 12,
    speed: 90,
    radius: 10,
    xp: 12,
    color: '#a855f7',
    behavior: 'chase',
  },
  skeleton: {
    id: 'skeleton',
    name: 'Skeleton',
    health: 50,
    damage: 15,
    speed: 55,
    radius: 16,
    xp: 18,
    color: '#e5e5e5',
    behavior: 'chase',
  },
  ghost: {
    id: 'ghost',
    name: 'Ghost',
    health: 40,
    damage: 20,
    speed: 70,
    radius: 14,
    xp: 25,
    color: '#94a3b8',
    behavior: 'phase', // Can move through other enemies
  },
  golem: {
    id: 'golem',
    name: 'Golem',
    health: 120,
    damage: 25,
    speed: 30,
    radius: 24,
    xp: 50,
    color: '#78716c',
    behavior: 'chase',
  },
  spider: {
    id: 'spider',
    name: 'Spider',
    health: 15,
    damage: 6,
    speed: 110,
    radius: 8,
    xp: 8,
    color: '#1f2937',
    behavior: 'swarm', // Spawns in groups
  },
  bomber: {
    id: 'bomber',
    name: 'Bomber',
    health: 25,
    damage: 10,
    speed: 65,
    radius: 12,
    xp: 20,
    color: '#f97316',
    behavior: 'explode', // Explodes on death
    explosionRadius: 80,
    explosionDamage: 30,
  },
  necromancer: {
    id: 'necromancer',
    name: 'Necromancer',
    health: 60,
    damage: 8,
    speed: 35,
    radius: 16,
    xp: 40,
    color: '#7c3aed',
    behavior: 'summon', // Summons minions
    summonCooldown: 5000,
    summonType: 'skeleton',
  },
  elemental: {
    id: 'elemental',
    name: 'Fire Elemental',
    health: 70,
    damage: 18,
    speed: 50,
    radius: 18,
    xp: 35,
    color: '#dc2626',
    behavior: 'chase',
    resistant: ['fireball', 'flamewave'], // Takes half damage
  },
  iceElemental: {
    id: 'iceElemental',
    name: 'Ice Elemental',
    health: 70,
    damage: 18,
    speed: 50,
    radius: 18,
    xp: 35,
    color: '#0ea5e9',
    behavior: 'chase',
    resistant: ['frostbolt', 'blizzard'],
  },
  mimic: {
    id: 'mimic',
    name: 'Mimic',
    health: 45,
    damage: 25,
    speed: 100,
    radius: 10,
    xp: 30,
    color: '#3b82f6', // Same as XP orb!
    behavior: 'ambush', // Disguised as XP orb
  },
  // MID-TIER MOBS - Tougher enemies between regular and boss
  thorn_beetle: {
    id: 'thorn_beetle',
    name: 'Thorn Beetle',
    health: 65,
    damage: 14,
    speed: 55,
    radius: 17,
    xp: 30,
    color: '#65a30d',
    behavior: 'chase',
  },
  meadow_golem: {
    id: 'meadow_golem',
    name: 'Mossy Golem',
    health: 120,
    damage: 18,
    speed: 30,
    radius: 26,
    xp: 50,
    color: '#4d7c0f',
    behavior: 'chase',
    armor: 2,
  },
  dire_wolf: {
    id: 'dire_wolf',
    name: 'Dire Wolf',
    health: 130,
    damage: 25,
    speed: 80,
    radius: 22,
    xp: 60,
    color: '#111827',
    behavior: 'chase',
  },
  lava_serpent: {
    id: 'lava_serpent',
    name: 'Lava Serpent',
    health: 160,
    damage: 30,
    speed: 65,
    radius: 16,
    xp: 70,
    color: '#ea580c',
    behavior: 'chase',
    burnOnTouch: true,
    burnDamage: 8,
  },
  frozen_sentinel: {
    id: 'frozen_sentinel',
    name: 'Frozen Sentinel',
    health: 220,
    damage: 35,
    speed: 35,
    radius: 28,
    xp: 110,
    color: '#bae6fd',
    behavior: 'chase',
    armor: 4,
  },
  abyssal_knight: {
    id: 'abyssal_knight',
    name: 'Abyssal Knight',
    health: 300,
    damage: 55,
    speed: 50,
    radius: 24,
    xp: 180,
    color: '#4c1d95',
    behavior: 'chase',
    armor: 6,
  },
  crystal_construct: {
    id: 'crystal_construct',
    name: 'Crystal Construct',
    health: 200,
    damage: 32,
    speed: 35,
    radius: 26,
    xp: 90,
    color: '#d946ef',
    behavior: 'chase',
    armor: 5,
    reflectDamage: 0.15,
  },
  skeleton_archer: {
    id: 'skeleton_archer',
    name: 'Skeleton Archer',
    health: 45,
    damage: 20,
    speed: 40,
    radius: 14,
    xp: 22,
    color: '#d4d4d4',
    behavior: 'ranged',
    projectileSpeed: 150,
    attackRange: 300,
    attackCooldown: 2000,
  },
  boss_slime: {
    id: 'boss_slime',
    name: 'King Slime',
    health: 500,
    damage: 20,
    speed: 35,
    radius: 40,
    xp: 200,
    color: '#22c55e',
    behavior: 'boss',
    isBoss: true,
  },
  // ZONE BOSSES - Unique per zone with custom attacks
  boss_meadow: {
    id: 'boss_meadow',
    name: 'Blossom Behemoth',
    health: 800,
    damage: 18,
    speed: 40,
    radius: 35,
    xp: 150,
    color: '#84cc16',
    behavior: 'boss_meadow',
    isBoss: true,
    zone: 'meadow',
    attackCooldown: 3000,
    attackType: 'spore_burst', // Spawns homing spores
  },
  boss_forest: {
    id: 'boss_forest',
    name: 'Ancient Treant',
    health: 1500,
    damage: 30,
    speed: 25,
    radius: 45,
    xp: 300,
    color: '#166534',
    behavior: 'boss_forest',
    isBoss: true,
    zone: 'forest',
    attackCooldown: 4000,
    attackType: 'root_trap', // Creates damaging root zones
  },
  boss_volcanic: {
    id: 'boss_volcanic',
    name: 'Magma Titan',
    health: 2200,
    damage: 40,
    speed: 30,
    radius: 50,
    xp: 500,
    color: '#dc2626',
    behavior: 'boss_volcanic',
    isBoss: true,
    zone: 'volcanic',
    attackCooldown: 5000,
    attackType: 'meteor_rain', // Calls down meteors around it
  },
  boss_frozen: {
    id: 'boss_frozen',
    name: 'Frost Wyrm',
    health: 3000,
    damage: 45,
    speed: 45,
    radius: 48,
    xp: 700,
    color: '#0ea5e9',
    behavior: 'boss_frozen',
    isBoss: true,
    zone: 'frozen',
    attackCooldown: 4000,
    attackType: 'ice_breath', // Cone attack that freezes
  },
  boss_abyss: {
    id: 'boss_abyss',
    name: 'Void Overlord',
    health: 5000,
    damage: 55,
    speed: 35,
    radius: 55,
    xp: 1500,
    color: '#581c87',
    behavior: 'boss_abyss',
    isBoss: true,
    zone: 'abyss',
    attackCooldown: 3500,
    attackType: 'void_pulse', // AOE that pulls players in then explodes
  },
  boss_crystal: {
    id: 'boss_crystal',
    name: 'Crystal Golem',
    health: 1200,
    damage: 25,
    speed: 30,
    radius: 40,
    xp: 250,
    color: '#ec4899',
    behavior: 'boss_crystal',
    isBoss: true,
    zone: 'crystal_caves',
    attackCooldown: 3500,
    attackType: 'crystal_barrage', // Shoots crystal shards
  },
  // DUNGEON ENEMIES - Dragon's Gauntlet
  dungeon_skeleton: {
    id: 'dungeon_skeleton',
    name: 'Cursed Knight',
    health: 200,
    damage: 35,
    speed: 60,
    radius: 18,
    xp: 80,
    color: '#44403c',
    behavior: 'chase',
    isDungeon: true,
  },
  dungeon_wraith: {
    id: 'dungeon_wraith',
    name: 'Soul Wraith',
    health: 150,
    damage: 45,
    speed: 85,
    radius: 16,
    xp: 100,
    color: '#3730a3',
    behavior: 'phase',
    isDungeon: true,
  },
  dungeon_golem: {
    id: 'dungeon_golem',
    name: 'Obsidian Guardian',
    health: 400,
    damage: 50,
    speed: 35,
    radius: 28,
    xp: 150,
    color: '#1c1917',
    behavior: 'chase',
    isDungeon: true,
  },
  dungeon_demon: {
    id: 'dungeon_demon',
    name: 'Infernal Demon',
    health: 300,
    damage: 60,
    speed: 70,
    radius: 22,
    xp: 200,
    color: '#7f1d1d',
    behavior: 'chase',
    isDungeon: true,
    attackCooldown: 3000,
    attackType: 'demon_fire', // Shoots fireballs
  },
  
  // DUNGEON MINI-BOSSES
  dungeon_minotaur: {
    id: 'dungeon_minotaur',
    name: 'Ironhide Minotaur',
    health: 5000,
    damage: 90,
    speed: 80,
    radius: 40,
    xp: 1200,
    color: '#78350f',
    behavior: 'charge',
    isMiniBoss: true,
    isDungeon: true,
    zone: 'dungeon',
    attackCooldown: 2500,
    chargeSpeed: 350,
    chargeDistance: 500,
  },
  dungeon_lich: {
    id: 'dungeon_lich',
    name: 'Lich King',
    health: 4000,
    damage: 70,
    speed: 55,
    radius: 32,
    xp: 1000,
    color: '#1e1b4b',
    behavior: 'caster',
    isMiniBoss: true,
    isDungeon: true,
    zone: 'dungeon',
    attackCooldown: 1800,
    summonCount: 4,
  },
  
  // DRAGON BOSS - Final boss of dungeon (2.5x bigger)
  boss_dragon: {
    id: 'boss_dragon',
    name: 'Infernal Dragon',
    health: 40000,
    damage: 150,
    speed: 55,
    radius: 80,
    xp: 15000,
    color: '#b91c1c',
    behavior: 'boss_dragon',
    isBoss: true,
    isDungeon: true,
    zone: 'dungeon',
    attackCooldown: 1500,
    attackRange: 800,
    attacks: ['flame_breath', 'wing_gust', 'tail_swipe', 'summon_minions', 'meteor_rain', 'rage_mode'],
  },
};


// Zone boss types (which boss for each zone)
export const ZONE_BOSS_TYPES = {
  meadow: 'boss_meadow',
  forest: 'boss_forest',
  volcanic: 'boss_volcanic',
  frozen: 'boss_frozen',
  abyss: 'boss_abyss',
  crystal_caves: 'boss_crystal',
};
