// ===========================================
// ENEMY & BOSS CONFIGURATION
// ===========================================

// Zone-specific enemy types
const ZONE_ENEMIES = {
  meadow: [
    {
      type: 'slime',
      name: 'Green Slime',
      health: 30,
      damage: 5,
      speed: 1.5,
      xp: 10,
      color: '#84cc16',
      radius: 15,
      behavior: 'wander',
    },
    {
      type: 'butterfly',
      name: 'Wicked Butterfly',
      health: 20,
      damage: 8,
      speed: 2.5,
      xp: 15,
      color: '#f472b6',
      radius: 12,
      behavior: 'erratic',
    },
    {
      type: 'flower_sprite',
      name: 'Flower Sprite',
      health: 40,
      damage: 10,
      speed: 1.2,
      xp: 20,
      color: '#fbbf24',
      radius: 14,
      behavior: 'ranged',
      projectileSpeed: 4,
    },
  ],
  
  forest: [
    {
      type: 'wolf',
      name: 'Shadow Wolf',
      health: 60,
      damage: 15,
      speed: 3,
      xp: 30,
      color: '#374151',
      radius: 18,
      behavior: 'pack',
      packSize: 3,
    },
    {
      type: 'spider',
      name: 'Giant Spider',
      health: 50,
      damage: 12,
      speed: 2.5,
      xp: 25,
      color: '#1f2937',
      radius: 20,
      behavior: 'ambush',
      webSlowAmount: 0.5,
    },
    {
      type: 'treant_minor',
      name: 'Young Treant',
      health: 100,
      damage: 20,
      speed: 1,
      xp: 45,
      color: '#166534',
      radius: 25,
      behavior: 'guard',
    },
    {
      type: 'wisp',
      name: 'Forest Wisp',
      health: 35,
      damage: 18,
      speed: 2,
      xp: 35,
      color: '#4ade80',
      radius: 10,
      behavior: 'ranged',
      projectileSpeed: 6,
      phaseThrough: true,
    },
  ],
  
  volcanic: [
    {
      type: 'fire_elemental',
      name: 'Fire Elemental',
      health: 80,
      damage: 25,
      speed: 2,
      xp: 50,
      color: '#f97316',
      radius: 18,
      behavior: 'chase',
      burnOnTouch: true,
      burnDamage: 5,
    },
    {
      type: 'magma_slime',
      name: 'Magma Slime',
      health: 120,
      damage: 20,
      speed: 1.2,
      xp: 55,
      color: '#dc2626',
      radius: 22,
      behavior: 'split',
      splitCount: 2,
    },
    {
      type: 'ember_bat',
      name: 'Ember Bat',
      health: 45,
      damage: 18,
      speed: 4,
      xp: 40,
      color: '#fbbf24',
      radius: 12,
      behavior: 'swarm',
    },
    {
      type: 'obsidian_golem',
      name: 'Obsidian Golem',
      health: 200,
      damage: 35,
      speed: 0.8,
      xp: 80,
      color: '#1c1917',
      radius: 30,
      behavior: 'guard',
      armor: 5,
    },
  ],
  
  frozen: [
    {
      type: 'ice_wraith',
      name: 'Ice Wraith',
      health: 70,
      damage: 22,
      speed: 2.5,
      xp: 60,
      color: '#67e8f9',
      radius: 16,
      behavior: 'phase',
      freezeOnHit: true,
      freezeDuration: 500,
    },
    {
      type: 'frost_wolf',
      name: 'Frost Wolf',
      health: 90,
      damage: 28,
      speed: 3.5,
      xp: 70,
      color: '#e0f2fe',
      radius: 20,
      behavior: 'pack',
      packSize: 4,
    },
    {
      type: 'yeti',
      name: 'Yeti',
      health: 180,
      damage: 40,
      speed: 1.5,
      xp: 100,
      color: '#f8fafc',
      radius: 32,
      behavior: 'charge',
      chargeSpeed: 6,
    },
    {
      type: 'ice_elemental',
      name: 'Ice Elemental',
      health: 100,
      damage: 30,
      speed: 1.8,
      xp: 75,
      color: '#22d3ee',
      radius: 20,
      behavior: 'ranged',
      projectileSpeed: 7,
      slowOnHit: 0.4,
    },
  ],
  
  abyss: [
    {
      type: 'shadow_fiend',
      name: 'Shadow Fiend',
      health: 120,
      damage: 35,
      speed: 3,
      xp: 90,
      color: '#581c87',
      radius: 18,
      behavior: 'teleport',
      teleportCooldown: 3000,
    },
    {
      type: 'void_stalker',
      name: 'Void Stalker',
      health: 150,
      damage: 45,
      speed: 2.5,
      xp: 120,
      color: '#3b0764',
      radius: 22,
      behavior: 'stealth',
      invisDuration: 2000,
    },
    {
      type: 'eldritch_horror',
      name: 'Eldritch Horror',
      health: 250,
      damage: 50,
      speed: 1,
      xp: 150,
      color: '#7c3aed',
      radius: 35,
      behavior: 'tentacles',
      tentacleCount: 4,
    },
    {
      type: 'void_eye',
      name: 'Void Eye',
      health: 80,
      damage: 40,
      speed: 1.5,
      xp: 100,
      color: '#a855f7',
      radius: 25,
      behavior: 'ranged',
      projectileSpeed: 8,
      beamAttack: true,
    },
  ],
  
  crystal_caves: [
    {
      type: 'crystal_spider',
      name: 'Crystal Spider',
      health: 65,
      damage: 20,
      speed: 2.8,
      xp: 45,
      color: '#f0abfc',
      radius: 16,
      behavior: 'ambush',
      reflectDamage: 0.1,
    },
    {
      type: 'gem_elemental',
      name: 'Gem Elemental',
      health: 110,
      damage: 28,
      speed: 1.5,
      xp: 65,
      color: '#ec4899',
      radius: 20,
      behavior: 'guard',
      armor: 3,
    },
    {
      type: 'prismatic_wisp',
      name: 'Prismatic Wisp',
      health: 50,
      damage: 25,
      speed: 3,
      xp: 55,
      color: '#f472b6',
      radius: 12,
      behavior: 'ranged',
      projectileSpeed: 9,
      multiShot: 3,
    },
  ],
};

// Boss definitions
const BOSSES = {
  blossom_behemoth: {
    type: 'blossom_behemoth',
    name: '🌸 Blossom Behemoth',
    zone: 'meadow',
    health: 2000,
    maxHealth: 2000,
    damage: 30,
    speed: 1.2,
    radius: 60,
    xp: 500,
    color: '#ec4899',
    phases: [
      { healthPercent: 1.0, attack: 'petal_storm' },
      { healthPercent: 0.5, attack: 'summon_sprites' },
      { healthPercent: 0.25, attack: 'enrage' },
    ],
    attacks: {
      petal_storm: {
        cooldown: 4000,
        damage: 15,
        projectiles: 12,
        speed: 5,
      },
      summon_sprites: {
        cooldown: 8000,
        summonCount: 4,
        summonType: 'flower_sprite',
      },
      vine_grab: {
        cooldown: 6000,
        range: 200,
        pullSpeed: 100,
      },
    },
  },
  
  ancient_treant: {
    type: 'ancient_treant',
    name: '🌲 Ancient Treant',
    zone: 'forest',
    health: 4000,
    maxHealth: 4000,
    damage: 40,
    speed: 0.8,
    radius: 80,
    xp: 800,
    color: '#166534',
    phases: [
      { healthPercent: 1.0, attack: 'root_attack' },
      { healthPercent: 0.6, attack: 'summon_treants' },
      { healthPercent: 0.3, attack: 'nature_wrath' },
    ],
    attacks: {
      root_attack: {
        cooldown: 3000,
        damage: 25,
        stunDuration: 1000,
        range: 300,
      },
      summon_treants: {
        cooldown: 10000,
        summonCount: 2,
        summonType: 'treant_minor',
      },
      nature_wrath: {
        cooldown: 5000,
        damage: 35,
        radius: 250,
      },
    },
  },
  
  magma_titan: {
    type: 'magma_titan',
    name: '🔥 Magma Titan',
    zone: 'volcanic',
    health: 6000,
    maxHealth: 6000,
    damage: 50,
    speed: 1,
    radius: 90,
    xp: 1200,
    color: '#f97316',
    phases: [
      { healthPercent: 1.0, attack: 'meteor_shower' },
      { healthPercent: 0.5, attack: 'lava_pool' },
      { healthPercent: 0.2, attack: 'volcanic_eruption' },
    ],
    attacks: {
      meteor_shower: {
        cooldown: 5000,
        damage: 40,
        meteorCount: 5,
        radius: 80,
      },
      lava_pool: {
        cooldown: 8000,
        damage: 15,
        duration: 6000,
        radius: 120,
      },
      volcanic_eruption: {
        cooldown: 12000,
        damage: 60,
        radius: 300,
        waveCount: 3,
      },
    },
  },
  
  frost_wyrm: {
    type: 'frost_wyrm',
    name: '❄️ Frost Wyrm',
    zone: 'frozen',
    health: 7000,
    maxHealth: 7000,
    damage: 55,
    speed: 1.5,
    radius: 85,
    xp: 1500,
    color: '#22d3ee',
    phases: [
      { healthPercent: 1.0, attack: 'frost_breath' },
      { healthPercent: 0.6, attack: 'blizzard' },
      { healthPercent: 0.25, attack: 'ice_tomb' },
    ],
    attacks: {
      frost_breath: {
        cooldown: 4000,
        damage: 30,
        coneAngle: Math.PI / 4,
        range: 350,
        slowAmount: 0.5,
      },
      blizzard: {
        cooldown: 10000,
        damage: 20,
        radius: 400,
        duration: 5000,
      },
      ice_tomb: {
        cooldown: 15000,
        freezeDuration: 3000,
        damage: 45,
      },
    },
  },
  
  void_overlord: {
    type: 'void_overlord',
    name: '🌀 Void Overlord',
    zone: 'abyss',
    health: 10000,
    maxHealth: 10000,
    damage: 70,
    speed: 1.2,
    radius: 100,
    xp: 2500,
    color: '#7c3aed',
    phases: [
      { healthPercent: 1.0, attack: 'void_missiles' },
      { healthPercent: 0.7, attack: 'summon_void' },
      { healthPercent: 0.4, attack: 'reality_warp' },
      { healthPercent: 0.15, attack: 'annihilation' },
    ],
    attacks: {
      void_missiles: {
        cooldown: 2000,
        damage: 35,
        projectiles: 8,
        speed: 6,
        homing: true,
      },
      summon_void: {
        cooldown: 12000,
        summonCount: 3,
        summonType: 'shadow_fiend',
      },
      reality_warp: {
        cooldown: 8000,
        teleportCount: 3,
        afterimageDamage: 40,
      },
      annihilation: {
        cooldown: 20000,
        damage: 100,
        radius: 500,
        chargeTime: 3000,
      },
    },
  },
  
  crystal_golem: {
    type: 'crystal_golem',
    name: '💎 Crystal Golem',
    zone: 'crystal_caves',
    health: 5000,
    maxHealth: 5000,
    damage: 45,
    speed: 0.9,
    radius: 75,
    xp: 1000,
    color: '#ec4899',
    phases: [
      { healthPercent: 1.0, attack: 'crystal_barrage' },
      { healthPercent: 0.5, attack: 'prism_shield' },
      { healthPercent: 0.2, attack: 'shatter_nova' },
    ],
    attacks: {
      crystal_barrage: {
        cooldown: 3000,
        damage: 25,
        projectiles: 6,
        bounceCount: 2,
      },
      prism_shield: {
        cooldown: 15000,
        duration: 5000,
        reflectDamage: 0.5,
      },
      shatter_nova: {
        cooldown: 10000,
        damage: 50,
        radius: 200,
        shardCount: 12,
      },
    },
  },
};

// Get enemies for a zone
function getZoneEnemies(zoneId) {
  return ZONE_ENEMIES[zoneId] || ZONE_ENEMIES.meadow;
}

// Get boss for a zone
function getZoneBoss(zoneId) {
  for (const boss of Object.values(BOSSES)) {
    if (boss.zone === zoneId) return boss;
  }
  return null;
}

// Select random enemy type for zone based on weights
function selectEnemyType(zoneId) {
  const enemies = getZoneEnemies(zoneId);
  return enemies[Math.floor(Math.random() * enemies.length)];
}

module.exports = {
  ZONE_ENEMIES,
  BOSSES,
  getZoneEnemies,
  getZoneBoss,
  selectEnemyType,
};
