// ===========================================
// SPELLS
// ===========================================

export const SPELLS = {
  fireball: {
    id: 'fireball',
    name: 'Fireball',
    damage: 28,
    cooldown: 900,
    range: 320,
    speed: 450,
    radius: 12,
    color: '#ff6b35',
    trailColor: '#ffaa00',
  },
  flamewave: {
    id: 'flamewave',
    name: 'Flame Wave',
    damage: 18,
    cooldown: 1500,
    range: 200,
    speed: 0, // AOE
    radius: 120,
    color: '#ff4500',
    isAoe: true,
  },
  frostbolt: {
    id: 'frostbolt',
    name: 'Frost Bolt',
    damage: 18,
    cooldown: 500,
    range: 280,
    speed: 550,
    radius: 8,
    color: '#4ecdc4',
    trailColor: '#a0e9e4',
    slowEffect: 0.5, // 50% slow
    slowDuration: 1500,
  },
  blizzard: {
    id: 'blizzard',
    name: 'Blizzard',
    damage: 12,
    cooldown: 2500,
    range: 250,
    speed: 0,
    radius: 150,
    color: '#87ceeb',
    isAoe: true,
    slowEffect: 0.3,
    slowDuration: 2000,
  },
  arcaneBlast: {
    id: 'arcaneBlast',
    name: 'Arcane Blast',
    damage: 45,
    cooldown: 2000,
    range: 180,
    speed: 0,
    radius: 100,
    color: '#9b5de5',
    isAoe: true,
  },
  magicMissile: {
    id: 'magicMissile',
    name: 'Magic Missile',
    damage: 15,
    cooldown: 400,
    range: 350,
    speed: 600,
    radius: 6,
    color: '#e056fd',
    trailColor: '#d63384',
    homing: true,
  },
  
  // === VOIDLORD SPELLS ===
  voidBolt: {
    id: 'voidBolt',
    name: 'Void Bolt',
    damage: 30,
    cooldown: 700,
    range: 350,
    speed: 500,
    radius: 12,
    color: '#1a0a2e',
    trailColor: '#ff00ff',
    piercing: true,
    isVoidBolt: true,
  },
  annihilate: {
    id: 'annihilate',
    name: 'Annihilate',
    damage: 45,
    cooldown: 2500,
    range: 300,
    speed: 0, // AOE
    radius: 120,
    color: '#ff00ff',
    isAoe: true,
  },
  
  // === SHADOW ARCHER SPELLS ===
  shadowArrow: {
    id: 'shadowArrow',
    name: 'Shadow Arrow',
    damage: 20,
    cooldown: 650,
    range: 480,
    speed: 750,
    radius: 8,
    color: '#0f172a',
    trailColor: '#dc2626',
    piercing: true,
    isArrow: true,
  },
  piercingVolley: {
    id: 'piercingVolley',
    name: 'Piercing Volley',
    damage: 35,
    cooldown: 2200,
    range: 380,
    speed: 0,
    radius: 140,
    color: '#dc2626',
    isAoe: true,
  },
  
  // === SWORDSMAN CLASS SPELLS ===
  daggerThrow: {
    id: 'daggerThrow',
    name: 'Dagger Throw',
    damage: 22,
    cooldown: 600,
    range: 400,
    speed: 700,
    radius: 8,
    color: '#708090',
    trailColor: '#c0c0c0',
  },
  axeHurl: {
    id: 'axeHurl',
    name: 'Axe Hurl',
    damage: 38,
    cooldown: 1500,
    range: 320,
    speed: 420,
    radius: 16,
    color: '#c0c0c0',
    trailColor: '#708090',
    piercing: true,
  },

  // === BRUTE CLASS SPELLS ===
  dumbbellThrow: {
    id: 'dumbbellThrow',
    name: 'Dumbbell Throw',
    damage: 32,
    cooldown: 900,
    range: 300,
    speed: 500,
    radius: 14,
    color: '#b45309',
    trailColor: '#fbbf24',
    piercing: true,
    isDumbbell: true,
  },
  groundPound: {
    id: 'groundPound',
    name: 'Ground Pound',
    damage: 40,
    cooldown: 2200,
    range: 0,
    speed: 0,
    radius: 180,
    color: '#fbbf24',
    isAoe: true,
  },
  
  // === PYROMANCER CLASS ABILITIES ===
  flameShield: {
    id: 'flameShield',
    name: 'Flame Shield',
    damage: 15,
    cooldown: 12000,
    range: 0,
    speed: 0,
    radius: 80,
    color: '#ff6b35',
    isAoe: true,
    duration: 5000,
    class: 'pyromancer',
    levelRequired: 10,
    hotkey: 1,
    description: 'Surround yourself with flames, damaging nearby enemies',
  },
  meteorStrike: {
    id: 'meteorStrike',
    name: 'Meteor Strike',
    damage: 80,
    cooldown: 18000,
    range: 350,
    speed: 0,
    radius: 100,
    color: '#ff4500',
    isAoe: true,
    delay: 1500,
    class: 'pyromancer',
    levelRequired: 20,
    hotkey: 2,
    description: 'Call down a devastating meteor from the sky',
  },
  inferno: {
    id: 'inferno',
    name: 'Inferno',
    damage: 150,
    cooldown: 45000,
    range: 0,
    speed: 0,
    radius: 250,
    color: '#ff0000',
    isAoe: true,
    class: 'pyromancer',
    levelRequired: 30,
    hotkey: 3,
    description: 'Unleash a massive explosion of fire around you',
  },

  // === CRYOMANCER CLASS ABILITIES ===
  frostNova: {
    id: 'frostNova',
    name: 'Frost Nova',
    damage: 25,
    cooldown: 10000,
    range: 0,
    speed: 0,
    radius: 120,
    color: '#00ffff',
    isAoe: true,
    freezeDuration: 3000,
    class: 'cryomancer',
    levelRequired: 10,
    hotkey: 1,
    description: 'Freeze all nearby enemies in place',
  },
  iceLance: {
    id: 'iceLance',
    name: 'Ice Lance',
    damage: 60,
    cooldown: 15000,
    range: 500,
    speed: 700,
    radius: 10,
    color: '#00ccff',
    trailColor: '#87ceeb',
    piercing: true,
    slowEffect: 0.8,
    slowDuration: 4000,
    class: 'cryomancer',
    levelRequired: 20,
    hotkey: 2,
    description: 'Pierce through enemies with a massive ice shard',
  },
  glacialStorm: {
    id: 'glacialStorm',
    name: 'Glacial Storm',
    damage: 40,
    cooldown: 40000,
    range: 300,
    speed: 0,
    radius: 200,
    color: '#b3e5fc',
    isAoe: true,
    duration: 6000,
    freezeDuration: 2000,
    class: 'cryomancer',
    levelRequired: 30,
    hotkey: 3,
    description: 'Summon a devastating blizzard that freezes all enemies',
  },

  // === ARCANIST CLASS ABILITIES ===
  blink: {
    id: 'blink',
    name: 'Blink',
    damage: 0,
    cooldown: 8000,
    range: 200,
    speed: 0,
    radius: 0,
    color: '#9b5de5',
    isTeleport: true,
    class: 'arcanist',
    levelRequired: 10,
    hotkey: 1,
    description: 'Instantly teleport a short distance',
  },
  arcaneBarrage: {
    id: 'arcaneBarrage',
    name: 'Arcane Barrage',
    damage: 30,
    cooldown: 14000,
    range: 400,
    speed: 500,
    radius: 8,
    color: '#e056fd',
    trailColor: '#9b5de5',
    homing: true,
    projectileCount: 5,
    class: 'arcanist',
    levelRequired: 20,
    hotkey: 2,
    description: 'Launch multiple homing arcane missiles',
  },
  timeWarp: {
    id: 'timeWarp',
    name: 'Time Warp',
    damage: 0,
    cooldown: 60000,
    range: 0,
    speed: 0,
    radius: 0,
    color: '#d4af37',
    duration: 8000,
    speedBoost: 1.5,
    cooldownReduction: 0.5,
    class: 'arcanist',
    levelRequired: 30,
    hotkey: 3,
    description: 'Warp time - gain massive speed and cooldown reduction',
  },

  // === STORMCALLER CLASS ABILITIES ===
  staticField: {
    id: 'staticField',
    name: 'Static Field',
    damage: 20,
    cooldown: 9000,
    range: 0,
    speed: 0,
    radius: 100,
    color: '#ffff00',
    isAoe: true,
    stunDuration: 1000,
    class: 'stormcaller',
    levelRequired: 10,
    hotkey: 1,
    description: 'Shock nearby enemies with electricity',
  },
  ballLightning: {
    id: 'ballLightning',
    name: 'Ball Lightning',
    damage: 100,
    cooldown: 16000,
    range: 500,
    speed: 150,
    radius: 30,
    color: '#ffd700',
    trailColor: '#ffff00',
    piercing: true,
    chainLightning: true,
    class: 'stormcaller',
    levelRequired: 20,
    hotkey: 2,
    description: 'Send a slow but devastating ball of lightning',
  },
  thunderGod: {
    id: 'thunderGod',
    name: 'Thunder God',
    damage: 200,
    cooldown: 50000,
    range: 0,
    speed: 0,
    radius: 350,
    color: '#ffffff',
    isAoe: true,
    chainCount: 8,
    class: 'stormcaller',
    levelRequired: 30,
    hotkey: 3,
    description: 'Call upon the fury of storms to devastate all enemies',
  },

  // === VOIDLORD CLASS ABILITIES ===
  voidRiftAbility: {
    id: 'voidRiftAbility',
    name: 'Void Rift',
    damage: 30,
    cooldown: 10000,
    range: 250,
    speed: 0,
    radius: 100,
    color: '#8b00ff',
    isAoe: true,
    duration: 3000,
    class: 'voidlord',
    levelRequired: 10,
    hotkey: 1,
    description: 'Tear open a rift to the void that damages enemies',
  },
  soulDrain: {
    id: 'soulDrain',
    name: 'Soul Drain',
    damage: 40,
    cooldown: 14000,
    range: 350,
    speed: 400,
    radius: 12,
    color: '#ff00ff',
    trailColor: '#8b008b',
    homing: true,
    lifesteal: 0.3,
    class: 'voidlord',
    levelRequired: 20,
    hotkey: 2,
    description: 'Launch a soul-seeking projectile that heals you',
  },
  apocalypse: {
    id: 'apocalypse',
    name: 'Apocalypse',
    damage: 120,
    cooldown: 45000,
    range: 0,
    speed: 0,
    radius: 250,
    color: '#1a0a2e',
    isAoe: true,
    class: 'voidlord',
    levelRequired: 30,
    hotkey: 3,
    description: 'Unleash the void to annihilate everything nearby',
  },
  
  // === SHADOW ARCHER CLASS ABILITIES ===
  huntersMark: {
    id: 'huntersMark',
    name: "Hunter's Mark",
    damage: 30,
    cooldown: 6000,
    range: 500,
    speed: 1200,
    radius: 8,
    color: '#dc2626',
    trailColor: '#991b1b',
    isArrow: true,
    piercing: true,
    class: 'shadowarcher',
    levelRequired: 10,
    hotkey: 1,
    description: 'Mark a target - next attacks deal bonus damage',
  },
  multishot: {
    id: 'multishot',
    name: 'Multishot',
    damage: 25,
    cooldown: 12000,
    range: 0,
    speed: 0,
    radius: 200,
    color: '#dc2626',
    isAoe: true,
    class: 'shadowarcher',
    levelRequired: 20,
    hotkey: 2,
    description: 'Fire arrows in all directions',
  },
  deathArrow: {
    id: 'deathArrow',
    name: 'Death Arrow',
    damage: 120,
    cooldown: 30000,
    range: 600,
    speed: 1200,
    radius: 12,
    color: '#000',
    trailColor: '#dc2626',
    isArrow: true,
    piercing: true,
    class: 'shadowarcher',
    levelRequired: 30,
    hotkey: 3,
    description: 'A devastating arrow that obliterates its target',
  },
  
  // === BRUTE CLASS UPGRADES ===
  proteinShake: {
    id: 'proteinShake',
    name: 'Protein Shake',
    damage: 0,
    cooldown: 15000,
    range: 0,
    speed: 0,
    radius: 120,
    color: '#fbbf24',
    isAoe: false,
    class: 'brute',
    levelRequired: 10,
    hotkey: 1,
    description: 'Chug a protein shake - heal 30% HP and gain speed boost',
  },
  barbellSpin: {
    id: 'barbellSpin',
    name: 'Barbell Spin',
    damage: 55,
    cooldown: 14000,
    range: 0,
    speed: 0,
    radius: 220,
    color: '#b45309',
    isAoe: true,
    class: 'brute',
    levelRequired: 20,
    hotkey: 2,
    description: 'Spin a barbell around you, crushing everything nearby',
  },
  ultimateFlex: {
    id: 'ultimateFlex',
    name: 'Ultimate Flex',
    damage: 130,
    cooldown: 42000,
    range: 0,
    speed: 0,
    radius: 250,
    color: '#fbbf24',
    isAoe: true,
    class: 'brute',
    levelRequired: 30,
    hotkey: 3,
    description: 'Flex so hard it creates a shockwave that decimates everything',
  },

  // === SWORDSMAN CLASS UPGRADES ===
  riposte: {
    id: 'riposte',
    name: 'Riposte',
    damage: 30,
    cooldown: 10000,
    range: 0,
    speed: 0,
    radius: 140,
    color: '#c0c0c0',
    isAoe: true,
    class: 'swordsman',
    levelRequired: 10,
    hotkey: 1,
    description: 'Parry and counter — brief invulnerability then strike back',
  },
  executionersStrike: {
    id: 'executionersStrike',
    name: "Executioner's Strike",
    damage: 65,
    cooldown: 16000,
    range: 0,
    speed: 0,
    radius: 170,
    color: '#708090',
    isAoe: true,
    class: 'swordsman',
    levelRequired: 20,
    hotkey: 2,
    description: 'A devastating overhead strike that cleaves through armor',
  },
  bladestorm: {
    id: 'bladestorm',
    name: 'Bladestorm',
    damage: 140,
    cooldown: 42000,
    range: 0,
    speed: 0,
    radius: 260,
    color: '#c0c0c0',
    isAoe: true,
    class: 'swordsman',
    levelRequired: 30,
    hotkey: 3,
    description: 'Unleash a whirlwind of steel, shredding everything in range',
  },
};

